version: "3.8"
services:
  ansible:
    container_name: ansible
    hostname: ansible
    tty: true
    volumes:
      - ~/src:/root/ansible
      - ~/.ssh/:/root/.ssh/
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SC_USERNAME: ${SC_USERNAME}
      SC_PASSWORD: ${SC_PASSWORD}
      SC_HOST: ${SC_HOST}